name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}

    steps:
      - name: Create Release PR or Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust

  publish-crates:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2
        with:
          shared-key: "ci"

      - name: Run tests
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --verbose --all-features

      - name: Security audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Package and publish
        run: |
          cargo package --verbose
          # Only publish if this version doesn't already exist
          if ! cargo search --limit 1 mdbook-lint | grep -q "$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "mdbook-lint") | .version')"; then
            cargo publish --verbose
          else
            echo "Version already published, skipping"
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build-binaries:
    name: Build Release Binaries
    runs-on: ${{ matrix.os }}
    needs: release-please
    if: needs.release-please.outputs.release_created
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: mdbook-lint
            asset_name: mdbook-lint-linux-x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: mdbook-lint
            asset_name: mdbook-lint-linux-x86_64-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: mdbook-lint.exe
            asset_name: mdbook-lint-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: mdbook-lint
            asset_name: mdbook-lint-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: mdbook-lint
            asset_name: mdbook-lint-macos-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/${{ matrix.binary_name }}

      - name: Upload binary to release
        run: |
          # Upload the binary to the release
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            target/${{ matrix.target }}/release/${{ matrix.binary_name }}#${{ matrix.asset_name }} \
            --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs: [release-please, publish-crates, build-binaries]
    if: needs.release-please.outputs.release_created

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build documentation
        run: |
          cargo doc --all-features --no-deps
          echo '<meta http-equiv="refresh" content="0; url=mdbook_lint">' > target/doc/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
